### ISSUE TITLE
Receiving "Unable to RSVP to Event that has Already Passed" Red Message Box when event hasn't passed

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#104]
Hi @JasonTheAdams ! So it was 5:30 p.m. today and I tried to RSVP 'no' for someone through [the Portal ](https://sdrefugeetutoring.com/volunteer-portal/upcoming-events) to the MS/HS tutoring event that starts at 6 p.m. But it gave me the message "Unable to RSVP to an event that has already passed." Couldn't RSVP 'yes' either! Not sure what time zone WP lives in, but it definitely isn't Pacific! This is so not good :( I definitely want people to be able to cancel and sign-up up until the last minute.
Please tell me it's an easy fix???

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

Good catch, and solid observation on the timezone — that's exactly what the issue was. It was using the wrong timezone (not the PT one set in WordPress) when checking the event date. I've resolved this in c84740d and tested it out. Let me know if you run into anything else!

Hope you're having a lovely Christmas season!
