### ISSUE TITLE
[CRITICAL URGENT] In Portal-Upcoming Events, default Tutoring Dates Category label needs to be changed from "Online Tutoring"

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#107]
Hey @JasonTheAdams  So under Volunteer Portal/Upcoming Events, the default Category label for Tutoring Dates says Online Tutoring. 

At this point, In-Person Tuesday Tutoring dates are unable to be published since they will be shown in the Portal as Online Tutoring. This will cause massive confusion 🥴 

Since the actual Event Title does not display in the Portal, we need to figure out a way to differentiate online tutoring dates from in-person tutoring dates. HELP!!!

![Screenshot_20230104-184606](https://user-images.githubusercontent.com/47679296/210694063-fe22979d-56f8-45ca-9b4d-a243c7f7f86d.png)

**Comment by JasonTheAdams** [comment]
Hey @dreazee!

Hah! Yeah, don't want to confuse folks about that. We've got a few options. Let me know what you think:
1. Just drop "online" so it says "Tutoring:"
2. Add an option on the event side where can mark an event as "In-Person" or "Online", which will be reflected here
3. Start including whether it's online or in-person in the title

The goal is to not confuse volunteers, so I feel like we should do 2, or 1 and 3. I'm leaning towards 2, that way we can surface whether an event is online or in-person in different ways in different contexts (i.e. Volunteer Portal, email, etc.). But if we just want to keep it simple, we can always just rely on the title and prefix it to be something like "Online: Middle & High School Tutoring".

I just looked and apparently you did exactly 3. Hahah! If you're happy with that, then we can stick with that. Otherwise, I could pretty easily do option 2 if you feel that's a better experience and helps keep the titles shorter.

**Comment by dreazee** [comment]
@JasonTheAdams These options are a bit confusing since the title doesn't show up in the Portal. That is something that would be great to have in the future for only the non-tutoring event category.
Great minds re: option 3! I included in the title so it is CRYSTAL clear when someone accesses the event in the Events Calendar and for me when I receive RSVP emails.

With Option 2, the whole "Online Tutoring" would need to be dropped. And it would be replaced with options, when creating an event, to mark exactly what type of event it is, is that correct? If so, we really should expand to the following 8 options:
Online Tutoring, In-Person Tutoring, Online Orientation, In-Person Orientation, In-Person Refresher, Online Refresher, In-Person Event, or Online Event (which probably won't happen again, but good to have).

I really want to get those In-Person dates up! If 2, when could that be implemented?

**Comment by JasonTheAdams** [comment]
I've implemented Option 2 in bb0668d. Now, when editing an event, there's a "Type of Event" dropdown to select from with the 8 options.

Since this is a new option, the Volunteer Portal will say "Event:" above the event category until it's updated in the admin — it won't be this way for new events moving forward that will have an "Event Type" out of the box.
