### ISSUE TITLE
URGENT - FIX CALENDAR EVENT RSVPs - NOT SHOWING UP IN RSVP ROSTER

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#118]
Hi @JasonTheAdams Figure this is a fallback from the update -- BIG issue happening with the RSVPs. If someone signs up for a session in the Calendar Event, it is not registering on the RSVP roster or in their Portal. If they sign up in the Portal, that still populates the RSVP Roster correctly. I saw this originally with Lilian Tran for today's session. Then tried it with my own login, too.

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

After some digging, I can confirm that this seems to be a regression in the recent updates to Gravity Forms. I've sent a detailed report of the issue to their support. If I'm able to come up with a workaround in the meantime I'll provide an update here.

Another option would be to swap out the RSVP form on the events page with a link to the volunteer portal and instructions.

**Comment by dreazee** [comment]
Thanks @JasonTheAdams
Let me think about this option of swapping out the form. I've figured out how to manage this for now & I'm going over the pros & cons of doing the swap. If support comes up empty-handed and there's no workaround, then I'll definitely do that. Until then I'm going to hold off a bit.

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

I'm happy to share this has been fixed. It turns out there was a breaking change in the recent Gravity Forms update. The short version is that the way the data was being gathered when creating the RSVP was no longer compatible. Fortunately, there was a simple and reliable workaround wherein the event id and start date are now retrieved when the form is first displayed, so it saves properly to the RSVP. The good news is that the reason they made the breaking change was in favor of making the form save faster, which is nice. Now that I know the limitations I can circumvent this in the future.

Please let me know if you hear of any further issues with this!

**Comment by dreazee** [comment]
@JasonTheAdams AWESOME NEWS!!! Thanks,  Jason 🙏
