### ISSUE TITLE
[VERY HIGH] Each school year, the roles for 'Volunteer' & 'Volunteer Minor' users needs to be reset

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#31]
At the beginning of each school year - at a date tbd (maybe Aug 1, if schools go year round) - the user role is reset so they are unable to RSVP until 3 criteria are fulfilled.
 
1. new background check
2. new code of conduct
3. refresher or orientation

As of now, this is all done by sight -  I must monitor incoming RSVPs from new and returning tutors and cross-check them with Refresher/Orientation attendance (and Checkr background checks if returning), and paper code of conduct forms on file and make sure those are completed.

**Comment by mathetos** [comment]
There's a bulk method to revert all the Volunteers and Volunteer Minors back to "Volunteer Pending". It's still a bit manual but should only take 5-10 minutes. 

Here's a video walkthrough for you of how to do it. I'll DM you on FB with the password (since there's email addresses in the video, I don't want the video being public).

https://screencast-o-matic.com/watch/cYioc65Wkw
