### ISSUE TITLE
Create a volunteer portal

### ISSUE THREAD

**Issue by mathetos** [SDRefugeeTutoring/sdrt-custom-functions#5]
I want to enable SDRT to be able to provide volunteers with a tax-deductible receipt of their volunteer hours they've donated in any given year.

**Comment by dreazee** [comment]
@JasonTheAdams Let's talk about ideas on how to expand the Volunteer Portal...

**Comment by dreazee** [comment]
An idea for the Volunteer Portal. 
-- personal calendar
--- Would love the RSVP system to have the functionality of the CBS pick-em app (I must pick a winner for ALL games before the app lets me save any of my picks). So we have the tutoring sessions laid out per week: Week 2 - Tuesday, Jan 18 and Thursday, Jan 20. One must choose an RSVP option to at least one session a week (even if that entry is a NO) So there isn't a way to RSVP for just one session. One must log in RSVPs for all 9 or 10 weeks of that trimester (except dates that have already passed) before they are able to click the "SAVE RSVPs" button at the bottom.

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

Taking some time to put together a proposal for this so we can get started! I'm not sure what "the CBS pick-em app" is. Would you mind breaking up your second point into steps? For example:
1. The volunteer sees all of the events for the current week
2. The volunteer has the ability to RSVP for an event right from the week view
3. Coordinators have the ability to view a volunteer's RSVP response reporting for a given trimester

Let's also break up a fews different topics:
1. The content and capabilities present on the Volunteer Portal
2. Flows that you would like to have (such as reporting on a volunteer's responses per trimester), and any automation we want as a part of that (e.g. emailing a volunteer if they haven't responded for 2 weeks).
3. Specific reporting that you'd like to have as the volunteer coordinator (likely as part of the flows)

At this point, I'm going to focus on the Volunteer Portal to flesh that out.

### Viewing Events & Trimesters
One thing I'm picking up from this that's interesting to me is the idea that events are grouped within trimesters. Perhaps we should design the portal to present events in this way. For example, having a list view of upcoming events where it shows all events within the current trimester.

We _could_ go the calendar route, but honestly calendars are complex and take a good amount of time to design. If we're working within the resolution of trimesters, then perhaps we can come up with a simple, easy view that lists out the events in a clear way on a per trimester basis.

I think the key feature here is the ability to:
- View upcoming events
- Provide a quick yes or no RSVP without having to view the event page

### Volunteer History
Next, it sounds like it would be beneficial for volunteers to be able to see a history of events that they've volunteered for. Should this be limited to events that the volunteer was confirmed as attending by a coordinator? That would make sense to me.

Perhaps we could include some encouraging/challenging stats back to volunteers:
- How long they've been a volunteer (starting from the first session)
- Total events attended
- Total hours given in tutoring
- % of events they said "yes" to but did not attend
- % of events that they attended in previous trimesters

### Profile Information
Finally, volunteers should have the ability to keep their profile and Volunteer Requirement Status (VRS) up-to-date:
- Ability to update their name and email
- Ability to view their VRS:
  - Background check status
  - Orientation status
  - Code of Conduct status
  - Volunteer Release status
- Ability to submit their background check
- View a list of upcoming orientations (and RSVP?)
- View and submit the Code of Conduct form
- View and submit the Volunteer Release & Waiver form

Ideally, volunteers should be able to handle the full VRS flow right from the Portal, or at least be provided links to what they need to do next (i.e. the forms).

---

I'm happy to hop on a call and discuss/brainstorm this! Otherwise, feel free to reply here and we'll keep the conversation moving along. 😃

**Comment by JasonTheAdams** [comment]
This project has been approved. I will provide updates here as they come in. The next step is for the designer to put together wireframes. I'll post them here for review and discussion once they're complete. I will also reach out on behalf of the designer should any questions arise that need answering which I'm not able to answer.
