### ISSUE TITLE
Fix Auto-Email sent after Attending Event (currently in html format)

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#51]
@JasonTheAdams  Hi Jason! Please see screenshot below. This is auto-email that is sent to volunteers after they are marked as attending, YOWZERZ!
![Screenshot (31)](https://user-images.githubusercontent.com/47679296/121436846-24568900-c936-11eb-9f42-b8dab14f754c.png)

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

Hmm, looks like the HTML is being encoded before being sent, as the image and links below are working. I'll take a look sometime in the next couple days!

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

I apologize it took me longer to get to this than I'd hoped. My wife started her Master's degree in the fall and it's really eaten up a lot of my margin. But! I finally figured out the issue and I believe I've resolved it.

SDRT uses the WP HTML Mail plugin, and something must have changed in an update. The plugin was checking for a special header to be applied to the outgoing email: `Content-Type: text/html`. What this does it tell receiving email clients that the email contains HTML which it should render (as opposed to a plain text email). Anyway, the WP HTML Mail plugin was taking it upon itself to check for the header and, if not present, to encode all the HTML into what are called HTML Entities — basically, a way making HTML characters (like < and >) show up as plain text instead of acting like real HTML.

When this plugin started doing that I'm not sure. As far as I can tell, the Content-Type header has never been applied to any of the outgoing SDRT emails. It _should_ be, as we are sending  HTML emails (but most email clients forgive this). So it's hard to tell when exactly this broke.

The solution was to add the Content-Type header to all of our outgoing emails. I believe I got them all, and I tested locally to confirm that the emails look correct. If you see any emails that don't look right, please let me know and I'll fix that one.

Since the fix was pretty straightforward (a944455) I'm going to close this Issue. If you find the issue again please comment here and I'll re-open and apply further fixes.

Hope you're having a great start of your summer!
