### ISSUE TITLE
Automated emails are being sent by info@ even though settings in Gravity Forms is set to be sent as admin@ 

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#63]
Similar to this issue:
https://github.com/SDRefugeeTutoring/sdrt-custom-functions/issues/58

However, RSVP emails in Gravity Forms IS set for outgoing mail to be sent as admin@ [1st screenshot] but it is being sent as info@ [2nd screenshot]
![Gravity-RSVP-admin](https://user-images.githubusercontent.com/47679296/144490944-50c04ccc-365c-47fa-857a-48e183613e54.png)
)
![RSVP-info@ sent](https://user-images.githubusercontent.com/47679296/144491528-08040256-3f88-46f4-9b34-a940718569dd.png)

So again this is clogging my andrea@ inbox, which I completely forgot would be an issue! So as soon as I receive the google login info for admin@ (see Slack DM), I will disable the andrea@ account from receiving admin@ emails.
But the info@ account—and therefore my andrea@ account— will still receive ALL of these RSVP, New User Reg, etc notices in the sent mail folder until this is resolved...

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

Please do the following and DM me the results:
1. Open up the email above
2. Click on the three vertical dots in the top-right of the email
3. Click "Show Original"
4. Select the big wall of text in the **bottom** section and copy it — send that to me

It's possible that because the email is going to the Info group, it looks like, to your personal email, that it's coming from the info@ group instead of from admin@. In other words the email is not going directly to you, but to info@, which then sends you an email — so from the perspective of your personal email, it _is_ coming from info@. 😆

**Comment by dreazee** [comment]
So how can this be fixed? Automated emails WERE being sent by admin@ before the email migration. They are now being sent by info@ even though the Gravity Forms settings haven't changed. Because of this, RSVP & New User Reg automated emails are once again populating the info@ SENT mail folder. (Not sure why I thought it wasn't.)
