### ISSUE TITLE
Orientation Event Pages not Displaying (or even registering) RSVP entries

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#64]
Alrighty, @JasonTheAdams  Here's another one for you! This one is interesting and hopefully has an easy fix!
New AND previous Orientation event pages are not displaying the RSVP entries. 
For example: https://sdrefugeetutoring.com/event/2022jan04-nto-training
![Orientation-Event-Page](https://user-images.githubusercontent.com/47679296/144901235-ac93d04b-6204-4dcf-be26-9ce7191c6dd7.png)
/
There are no RSVP entries listed under this event.
But I have received many RSVP automated emails. So in looking in the RSVP section in WP, you can see there are 27 RSVP entries that should be displayed underneath the Orientation Form
![RSVP-Entries](https://user-images.githubusercontent.com/47679296/144901533-5c51a2fe-e4de-48bf-aa87-e65aa5685fb5.png)
.

I changed the Event Category to Tutoring and the RSVP entries still weren't displaying, so it seems like something got knocked out of place in the coding for the Orientation forms settings?

**Comment by JasonTheAdams** [comment]
@dreazee All fixed! Turns out there's a difference between event RSVP's and orientations. We provided the option to specify whether they are or are not attending an event, as such the RSVPs on the event pages were being filtered to only show those that said they are attending. This broke orientations as it's the assumed the person is attending, which means it's not recorded whether they said they were or not.

Now only non-orientation event RSVPs are limited by volunteers marked as attending. Orientations show all RSVPs.
