### ISSUE TITLE
Change Orientation RSVP List to Last Name First

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#65]
Hi @JasonTheAdams Found another funny thing that must have gotten tweaked when we moved to gravity forms. The RSVP list on the Orientation event page is listed by first name instead of last name. So if you would be able to change that to list it by last name (same as Tutoring event pages) that would be awesome.
Here's the Orientation event page:
https://sdrefugeetutoring.com/event/2022jan04-nto-training/

**Comment by JasonTheAdams** [comment]
@dreazee Turns out this was specific to Orientations, as regular RSVPs were arranged correctly. The names will be in the correct "Last, First" format, which will order them properly moving forward. Existing orientations will be the "First Last" format that you currently see. Fixing existing Orientations would be a bit tedious, so I'd rather not do it unless you feel it's necessary — no worries if it is.

So what do you think? Are we good to simply move forward correctly? Or should I correct the existing entries?

**Comment by dreazee** [comment]
@JasonTheAdams  Good to know it was an easy fix for future Orientations. No worries about this current existing Orientation, not worth the hassle!
