### ISSUE TITLE
[SUPER HIGH PRIORITY] Email sign-up form issues

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#70]
@JasonTheAdams The form on the[ website here](https://sdrefugeetutoring.com/news/) is not working. 
When submitting the form on the News page, a message stating that the form submission was successful IS produced. But then there is no record of them on the Mailchimp contact list. In the last week+ I have signed up four people using the form on the News page and there was no record of them on the Contact List in Mailchimp.
 
BUT - I just checked the form on the bottom of our home page and that produces a successful email list sign-up!

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

All set! Apparently this form was missed during the migration from Caldera Forms to Gravity Forms. It was tucked away as a widget on the news page, so I wouldn't have found it unless I knew to look for it. Oops! The home page is using a completely different system via Beaver Builder, which is why it's continued to work.

I've replaced the Caldera widget with the Gravity Forms widget and confirmed that it's working properly. I used a real email to go through the double opt-in flow, and confirmed seeing it in MailChimp.

Let me know if you find anything else!
