### ISSUE TITLE
[SUPER HIGH PRIORITY] Integration of Mailchimp Signup to Registration Form

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#71]
@JasonTheAdams  It was my understanding that this has been a thing for a while (like years if I can remember correctly!), but it isn't. We need ASAP an automatic sign-up to Mailchimp newsletter/addition to Mailchimp Audience List upon filling out Registration Form.

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

I'm afraid this hasn't been in place since we switched to Gravity Forms quite some time ago. Looking back at the Caldera registration form, I don't see that in place there, either. Whatever the case, we clearly want it now. 😃

I've added the integration to Gravity Forms, and included the integration with the [registration form](https://sdrefugeetutoring.com/volunteer/). It sounds like you want this to be an automatic part of registration, so I added a required consent checkbox to the form so users are aware that by registering they're being added to a mailing list. Please review the field in the form and let me know if you'd like me to adjust the wording.

I enabled "double opt-in" for the form as well, so the user will be emailed an additional consent before they're finally added to the list. This is becoming legally required for data privacy regulations — California being on the higher edge of which — so we should probably keep it this way.

Lastly, I didn't see a "MailChimp Audience List" as you mentioned, but I did see a "SD Refugee Tutoring News" audience, so I used that. The other three audiences no longer seem relevant.

**Comment by JasonTheAdams** [comment]
Ah! Also, @dreazee, do we want this to apply to the minor registration form as well?

**Comment by dreazee** [comment]
@JasonTheAdams 
1. Fantastic! 

       OLD: "Being added to our list better gives us a way of coordinating with our volunteers."
       NEW: "Being added to our list gives us an easy way to keep our volunteers up-to-date with SDRT happenings."

How does that sound??

2. Should we add a line to let them know it's a double opt-in? So they check their inbox. Like: "Please check your email for the link to complete your newsletter subscription."

 3. Oh yes, I just meant the new volunteers' emails aren't being added to our "Audience". That SD REFUGEE TUTORING NEWS is our main Audience.

 4. No need for minor registration. All minors fill out the main registration form, too.

**Comment by JasonTheAdams** [comment]
Wonderful! I've updated the wording to include what you've mentioned, as well as informing them about the consent email.

I think this is good to go!

**Comment by dreazee** [comment]
@JasonTheAdams  Awesome! Thanks, Jason
