### ISSUE TITLE
[SUPER HIGH] VOLUNTEER PORTAL: UPCOMING EVENTS - Orientations (and all events) need to be displayed

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#76]
@JasonTheAdams Let's have all event categories be displayed in the volunteer portal on the "Upcoming Event" page.
https://sdrefugeetutoring.com/volunteer-portal/upcoming-events
Right now nothing is displayed, not even the Volunteer Portal menu bar, even though Orientation dates have been posted.

**Comment by JasonTheAdams** [comment]
@dreazee The idea was that the orientations would be displayed in the "Requirements" section for Volunteers that still needed to attend an orientation. Otherwise, volunteers may RSVP as "no" to a bunch of orientations that don't need to worry about. Is there a reason why a volunteer would need to be aware of orientation dates after they've attended one?

**Comment by dreazee** [comment]
@JasonTheAdams Just to be able to tell other people about them. But if they are that engaged that they want to share with friends, they probably are already hearing about the orientations the many other ways we communicate with tutors. 
Okay, let's have them only listed in the Volunteer Requirements - Orientation section!
