### ISSUE TITLE
[EXTREME HIGH PRIORITY] VOLUNTEER PORTAL - Volunteer Requirement - Remove capability for tutor to RSVP for ORIENTATION thru Portal?

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#84]
@JasonTheAdams It is awesome to be able to RSVP for an Orientation with the click of a button through the Volunteer Portal, but by doing this two of the four form entries are being bypassed and only the First/Last Name and Email Address would be logged in. Also, a lot of  detailed information on the Event Page could be potentially overlooked. 

So really the "MORE INFO" and "RSVP" button would be combined so that all the details would be read and the full RSVP form would be filled out through that event page.

Let me know what you think about all of this.... 

https://sdrefugeetutoring.com/volunteer-portal/requirements/

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

Wow, that's a good catch. Perhaps in the future we can display the form in a modal when they click "RSVP", but for the sake of time I did something simple that I think is helpful. I left the "RSVP" button and now when you click on it you're taken to the orientation event page **directly** to the form. I figure if the user knows they want to attend then we can just jump them straight to the form instead of making them scroll down to find it.

Let me know if you think that's a bad user experience for some reason. 😄

**Comment by dreazee** [comment]
@JasonTheAdams  Love this simple fix! BUT I just tested this Orientation RSVP and it is still processing the RSVP the same way - automatically instead of being redirected to the RSVP form on the Orientation Event Page.

**Comment by JasonTheAdams** [comment]
@dreazee When you tested it your browser used the old (cached) version of the script. After loading the page make sure to refresh it again to prompt your browser to load the new scripts. I need to make improvements to how the scripts are loaded to prevent old versions from loading (called "cache busting").

**Comment by JasonTheAdams** [comment]
As mentioned in the other Issue, this should be working now as I've added cache busting. Let me know if this is working as intended.

**Comment by dreazee** [comment]
@JasonTheAdams  YES! This is working now! I promise I did multiple refreshes of the browser before writing my last comment :) Cache Busting saved the day.
